import NavBar from "@/components/NavBar";
import { Inter } from "next/font/google";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="${inter.className,}">
      <body className="">
        <main>
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
