"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 BerthaCar.glb --types
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube020: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube020_2: THREE.Mesh;
    Cube020_3: THREE.Mesh;
    Cube020_4: THREE.Mesh;
    Cube020_5: THREE.Mesh;
    Cube020_6: THREE.Mesh;
    Cube020_7: THREE.Mesh;
    Cube020_8: THREE.Mesh;
    Cube020_9: THREE.Mesh;
    Cube020_10: THREE.Mesh;
    Cube020_11: THREE.Mesh;
    Cube020_12: THREE.Mesh;
    Cube020_13: THREE.Mesh;
    Cube020_14: THREE.Mesh;
    Cube020_15: THREE.Mesh;
  };
  materials: {
    Solar: THREE.MeshStandardMaterial;
    Fan: THREE.MeshStandardMaterial;
    ["Black Metal"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    Body: THREE.MeshStandardMaterial;
    WindScreen: THREE.MeshStandardMaterial;
    FrontLights: THREE.MeshPhysicalMaterial;
    Back_Light: THREE.MeshPhysicalMaterial;
    Handle: THREE.MeshStandardMaterial;
    Low: THREE.MeshStandardMaterial;
    retro: THREE.MeshStandardMaterial;
    TireCenter: THREE.MeshStandardMaterial;
    Tire: THREE.MeshStandardMaterial;
    ["License BG"]: THREE.MeshStandardMaterial;
    ["License Blue"]: THREE.MeshStandardMaterial;
    ["License Red"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "CameraAction" | "CarAction.001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/BerthaCar.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Camera"
          position={[11, 7.5, 11]}
          rotation={[1.25, 0.3, -0.74]}
          scale={[0.77, 0.48, 1.84]}
        />
        <group name="Car" position={[0.01, 1.16, -0.02]}>
          <mesh
            castShadow
            receiveShadow
            name="Cube020"
            geometry={nodes.Cube020.geometry}
            material={materials.Solar}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_1"
            geometry={nodes.Cube020_1.geometry}
            material={materials.Fan}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_2"
            geometry={nodes.Cube020_2.geometry}
            material={materials["Black Metal"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_3"
            geometry={nodes.Cube020_3.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_4"
            geometry={nodes.Cube020_4.geometry}
            material={materials.Body}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_5"
            geometry={nodes.Cube020_5.geometry}
            material={materials.WindScreen}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_6"
            geometry={nodes.Cube020_6.geometry}
            material={materials.FrontLights}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_7"
            geometry={nodes.Cube020_7.geometry}
            material={materials.Back_Light}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_8"
            geometry={nodes.Cube020_8.geometry}
            material={materials.Handle}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_9"
            geometry={nodes.Cube020_9.geometry}
            material={materials.Low}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_10"
            geometry={nodes.Cube020_10.geometry}
            material={materials.retro}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_11"
            geometry={nodes.Cube020_11.geometry}
            material={materials.TireCenter}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_12"
            geometry={nodes.Cube020_12.geometry}
            material={materials.Tire}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_13"
            geometry={nodes.Cube020_13.geometry}
            material={materials["License BG"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_14"
            geometry={nodes.Cube020_14.geometry}
            material={materials["License Blue"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube020_15"
            geometry={nodes.Cube020_15.geometry}
            material={materials["License Red"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/BerthaCar.glb");
